### ISSUE TITLE
Upvoting issue in PlanView

### ISSUE THREAD

**Issue by Vielheim** [Vielheim/TourMate#123]
Sometimes when we downvote, it still shows as upvoted in PlanView. But when we navigate to TripView, it shows that we are downvoted

**Comment by Vielheim** [comment]
Not very sure of the cause, but seen in #121

**Comment by Vielheim** [comment]
After upvoting, there were multiple fetches and updates. Then for some weird reason my name is appended to the last update. 

![Screenshot 2022-04-03 at 00 14 41](https://user-images.githubusercontent.com/45381509/161391703-21126bcf-0350-4ae5-9bcc-fc46f7a7f594.png)

**Comment by Vielheim** [comment]
Linked to #130

**Comment by keanecjy** [comment]
There seems to be a more serious issue now, the listener on the plan view is constantly attaching and detaching itself when we upvote / downvote when there are more than 2 users.

I suspect it might be how the UpvotedUsersView or the upvoting logic is implemented.
