### ISSUE TITLE
Clean up Code base

### ISSUE THREAD

**Issue by Vielheim** [Vielheim/TourMate#51]
- Standardise Views for Plans and Trips:
Proposed idea: Plan/Trip Views > Add/Edit Views > Form Views

~~- Check classes are named appropriately for consistency:~~
~~E.g. We have a FirebaseTripController vs a PlanPersistenceController~~
~~Maybe we can standardise what a `Manager`, `Controller`, and `ViewModel` are and their responsibilities.~~
~~- E.g. who creates the Domain Model (ViewModel? Views? Controller?) and who passes what information to who and who does what checks~~

**Comment by rlrh** [comment]
Classes have been named consistently in #59
