### ISSUE TITLE
Create specific persistence managers for trip and plan

### ISSUE THREAD

**Issue by keanecjy** [Vielheim/TourMate#53]
This is so that we don't have to pass in the field / path.
Also this allows us to call specific fetchTrip / fetchPlan methods from the backend

**Comment by Vielheim** [comment]
The issue stems from the Plans being arranged as: Documents > Base > Super
whereas for Trips they are: Documents > Base

Retrieving the plan information require us to have an additional FieldPath in FirebasePersistenceManager.

Alternative by Ruiquan is to fix the encode/decode of plans

**Comment by Vielheim** [comment]
After discussion: Add a new layer to pass in the FieldPath

**Comment by keanecjy** [comment]
Remove super in fieldpath(s), so everyone should have the same fieldpath
