### ISSUE TITLE
Pagination idea

### ISSUE THREAD

**Issue by Vielheim** [Vielheim/TourMate#91]
Just leaving it here because its a passing thought that I had while doing the comments. Perhaps we can do something like a paging scheme to retrieve X number of items from the database, then when we want to load more, it will retrieve another X items. I'm not sure if its a SWE kind of engineering or just an optimisation.
- Imagine if we had like 1,000 comments then we retrieved it all, it might be quite laggy? 
- Can also be applied to plans, trips etc.

**Comment by keanecjy** [comment]
I think Prof would probably consider this as database optimization? He does not really care about this imo

**Comment by tanruiquan** [comment]
Yea I don't think it would be necessary as well since we wouldn't end up with a lot of comments for our demo anyways
